### ISSUE TITLE
Allow freezing or locking of configuration from future alteration

### ISSUE THREAD

**Issue by mehcode** [mehcode/config-rs#2]
A `Config` instance should allow locking to prevent all future mutation. Sources would need to support some kind of roll-up.

```rust
config::freeze();
config::set("key", "value"); // does nothing and returns an error
```

**Comment by nugend** [comment]
Is it possible to make a compile time option to panic or return a Result?

**Comment by tmccombs** [comment]
What if a `Config` instance had a  method like `fn freeze(self) -> ConfigView` that returned a `ConfigView` that only had read methods on it. Since it takes ownership of the config, the type and borrow checkers can enforce that the config is actually frozen.

That wouldn't work for the global config though. But maybe the global config should be removed (as mentioned in #17).

**Comment by mehcode** [comment]
Another thought to consider is how necessary this is. 

```rust
#[derive(Deserialize)]
struct AppConfig { ... }

fn main() {
  // Setup config via config::merge [...]
  let c: AppConfig = config::get("$");
}
```

If something similar to the above is supported, perhaps we don't need a way to freeze the underlying config store.

@SergioBenitez I added this issue because you expressed a strong desire to have a frozen configuration. What do you think?

**Comment by mehcode** [comment]
Closing this because deserialization is essentially freeze
