### ISSUE TITLE
Does it only accept key:value mode configuration?

### ISSUE THREAD

**Issue by jiashiwen** [mehcode/config-rs#243]
I add new line 
```
arry = ["a", "b", "c"]
```
to Settings.toml and got a error
```
Ok("/Users/jiashiwen/rustproject/clisample/target/debug/examples/configrs")
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: invalid type: sequence, expected a string for key `arry` in Settings.toml', examples/configrs.rs:18:61
```

**Comment by matthiasbeyer** [comment]
Could you share your code so we can see what you're doing?

**Comment by salieri11** [comment]
I have similar issue. My TOML file is:

[config]
version = 0.1

My code:
let mut settings = Config::default();
settings.merge(config::File::with_name(path)).unwrap();
 let hm = settings.try_into::<HashMap<String, String>>().unwrap();

It fails with:
panicked at 'called `Result::unwrap()` on an `Err` value: invalid type: map, expected a string for key `config`'

If I remove the [config] line, it works fine. I am using version 0.11

**Comment by matthiasbeyer** [comment]
@salieri11 your config file looks like this:

```
[config]
version = 0.1
```

? That would be a `HashMap<String, HashMap<String, f64>>` then, I guess?

**Comment by salieri11** [comment]
Hmmm I didnt get it.. I thought that everything is converted to String, since IMO it's more intuitive. In the case it works as you describe, I assume there are only 2 options:

-    to have everything as String in the config file (e.g. "0.1")
-    to modify code every time config file changes with new value types being added

Another point, I was expecting that the library will parse any depth of nested tables and then the key will be something like "config.version". Doesn't it work in this way?

**Comment by matthiasbeyer** [comment]
> Hmmm I didnt get it.. I thought that everything is converted to String, since IMO it's more intuitive

But you specified the value `0.1` in the TOML as a float. If you want to have it as a String, you'd need some quotes! :laughing: Like so:

```toml
[config]
version = "0.1"
```

> to modify code every time config file changes with new value types being added

Yes of course, otherwise your code won't know what you're trying to fetch, would it?

> Another point, I was expecting that the library will parse any depth of nested tables and then the key will be something like "config.version". Doesn't it work in this way?

It definitively does, via serde.

Try this:

```rust
#[derive(serde::Deserialize)]
struct VersionSetting {
    version: String
}

#[derive(serde::Deserialize)]
struct Config {
    config: VersionSetting,
}

let mut settings = Config::default();
settings.merge(config::File::with_name(path)).unwrap();
let config: Config = settings.try_into().unwrap();
```

The above types should represent the configuration format you wrote.

**Comment by salieri11** [comment]
OK thank you!

**Comment by polarathene** [comment]
Closing as issue appears to be resolved.
