### ISSUE TITLE
Handling config option renames

### ISSUE THREAD

**Issue by sunshowers** [mehcode/config-rs#284]
Hi there -- thanks for writing config! I use it for some of my own projects and it works quite well :)

While discussing this library with some folks, one of the things that came up was handling situations where config options were renamed. For example, consider a situation where config `path1.foo` is renamed to `path2.bar`, while there's still support for the old config name for backwards compatibility. It seems like there should be a way to tell config that `path1.foo` is the same as `path2.bar`, so that layering and overrides work as expected.

**Comment by sunshowers** [comment]
I'm wondering if the right way to do this is to add another layer of indirection while processing the config:

Something like:

* `Config::rename_fields`: new method to rename config options.
* (methods for other transformations to apply?)
* `Config::finalize()`: returns a new `MergedConfig` type that has field renames merged.

Then all the `get` methods, and `try_into`, move to being on `MergedConfig`. `try_from` continues to be on `Config` to act as a source.

**Comment by matthiasbeyer** [comment]
Hi!

I see where you're coming from and why this might be desirable, though I would not implement it because it introduces a high degree of additional complexity to this library. There would be need for code to handle certain situations: Think of if the user set both fields, but to different values - which one is the right one? Or if the renamed field was renamed again (possibly in another layer). This is way to complex to be in the library IMO. Others might disagree though :laughing: !

From what I understand, you can still do this "client side": After loading a layer, you can check if `path1.bar` was set. If it was, but is now renamed to `path2.bar`, you can notify the user (e.g. a warning), then set `path2.bar` manually to the value of `path1.bar` and go from there.

Hopy I could help you a bit with this. :wave:

**Comment by sunshowers** [comment]
Ahh yeah, I totally see what you mean. This can get pretty complex and there are several degrees of freedom involved.

I'm going to dig further into the client-side renaming feature. I'm happy to close this, thanks!
