### ISSUE TITLE
[Feature request] Considering add .set_default_with_range for integer & float type configs

### ISSUE THREAD

**Issue by JackLiar** [mehcode/config-rs#305]
It is quite common to have extra range requirement for integer & float types. Without this feature, crate users may have to write lots of codes to check whether the int/float value is in the expecting range.

for example

```rust
let value = cfg.get_int("key")?;
if value <= 1 || value >= 20 {
    // Error handing
}
```

what I'm expecting
```rust
let range = std::ops::Range { start: 1, end: 20};
// If test is out of range, return an Err
Config::builder(). set_default_with_range("test", 10, range)?;
```

Of course there are other requirements that are more complex than this, for example: is power of 2, less than or greater than, etc.

Maybe we could design another api to allow users to pass some simple custom validation function to the ConfigBuilder?

**Comment by matthiasbeyer** [comment]
Hi,

Thanks for opening this issue. I thought a bit about your case here and came to the conclusion that this is rather orthogonal to the usecase of this library. How about using a library for validation, such as [validator](https://docs.rs/validator/latest/validator/) (or others, there are plenty out there) for this?

You could deserialize your configuration into an object and then validate it with your needs using this library. I feel like this is the right approach to the problem, rather than putting more code into `config-rs`.

What do you think?

**Comment by JackLiar** [comment]
Thx for ur reply. I see ur point here. I didn't know there are crates like validator in crates.io, it looks interesting, I'll consider it in the future.
