### ISSUE TITLE
ConfigResult is undocumented, unwieldy and confusing

### ISSUE THREAD

**Issue by Jascha-N** [mehcode/config-rs#36]
Why do some functions return this **undocumented** pseudo-`Result` type? It makes normal Rust-like error handling a pain. I expected `ConfigResult` to be an alias for `Result<T, ConfigError>`, but it's not. I had to dig through the source code to find out what it actually is. It does not work with `try!` or the `?` operator  and does not expose any methods to turn it into an ordinary `Result`. It makes working with error handling crates such as `error-chain` extremely unwieldy. I assume it's supposed to be used to chain method calls, but even then there is no "terminal" method  (`deserialize`?) other than `unwrap`/`expect`, which is just bad practice. Why not used an ordinary `Result` type and use `?` to chain calls together instead of having a specialized, undocumented and panic-based `ConfigResult` type?

Right now, I have to do something silly like this:

```rust
if let Some(err) = config.foo().bar().err() {
    return Err(err);
}
```

Instead of just:

```rust
config.foo()?.bar()?;
```

**Comment by mehcode** [comment]
> Why do some functions return this undocumented pseudo-Result type?  [...]

`Config::merge` takes `&mut self`. If it took `mut self` I could add a Deref to `Result<Config>` and most things would happily work (or just return `Result`). It doesn't take `mut self` because that would preclude a global config instance.

Because of `&mut self`, your example would be:

```rust
config.foo()?.bar()?.clone()
```

Which feels really strange to write (to me, because of the clone). 

> [...] but even then there is no "terminal" method [...]

I did forget to add `deserialize` at least. I think because of #34 it wasn't on my mind.

I do intend to make `ConfigResult` more complete. I'll at least add a `.to_result` method.

> [...] than unwrap/expect, which is just bad practice [...]

Would you mind showing me how you're using Config? I'm curious. So far I've used it to setup configuration either globally or in the beginning of main (and then passed into a request guard in Rocket). In both of my situations, there is nothing wrong with `unwrap` usage.

---

As an aside, your tone is a little harsh. I apologize if I've caused you any anguish. I make no guarantee of this library and it certainly isn't stable yet.

**Comment by mehcode** [comment]
@Jascha-N I added 

 - `ConfigResult::to_result(self)` 
 - `ConfigResult::deserialize(self)` 

And several more forwarding methods to make it behave closer to Result.

I can't make `?` work without `#[feature(try_trait)]` and I don't want the lib to be nightly.

**Comment by Jascha-N** [comment]
Sorry for sounding harsh, but I wasted half an afternoon trying to figure out why a `FooResult` (a typical way to alias a `Result` type for a crate`foo`, e.g. `type FooResult<T> = Result<T, FooError>`) did not function as a `Result`. Only to find out hours later after I started digging through the code and had already made a pull request, the reason `ConfigResult` did not implement `ResultExt` (from `error-chain`) or `Try`/`Carrier` was because it was not an alias of `Result` at all! It would not have been a problem if `ConfigResult` showed up in the docs, but it did not, so it didn't even cross my mind that this type named "Result" was not actually a `Result`. (I'm not talking about written documentation here, it does not show up *at all* in the docs, because it is not exported from the crate.)

With regards to the implementation, I'm probably missing something, but I still don't see the need to have a specialized `ConfigResult`. What's wrong with returning `Result<&mut Self>`? Like so (greatly simplified):

```rust
impl Config {
    pub fn new() -> Config {
        /* ... */
    }

    pub fn set_default(&mut self, key: &str, val: &str) -> Result<&mut Self> {
        /* ... */
    }

    pub fn deserialize<T: Deserialize>(&self) -> Result<T> {
        /* ... */
    }
}

fn baz() -> Result<()> {
    Config::new()
           .set_default("foo", "bar")?
           .set_default("bar", "foo")?
           .serialize()?;

    // or:

    let mut config = Config::new();
    config.set_default("foo", "bar")?;
    config.set_default("bar", "foo")?;
    config.serialize()?;

    Ok(())
}
```

Or is the reason for `ConfigResult` to exist to hide the existence of `clone`? The `clone` is not even necessary if the user spreads out the code across multiple lines, e.g.:

```rust
fn baz() -> Result<()> {
    let mut config = Config::new();
    config.set_default("foo", "bar")?
          .set_default("bar", "foo")?;
    do_something(config)
}
```

I also don't agree that there is nothing wrong with `unwrap` usage. Panics (including those caused by `unwrap` and other assertions) are used to indicate a programming error, in quick testing or in cases where using a normal `Result` is impossible (rare). A malformed configuration file or a file missing from the user's system is not a programming error. I don't want to show the user a hard to read panic message and kill the entire thread/process, because they accidentally mistyped the name of a file.

**Comment by tmccombs** [comment]
> In both of my situations, there is nothing wrong with unwrap usage.
Even if the location of the configuration file is hard-coded, the application may want to manually handle the errors if for example the configuration file is missing to give the user a friendlier error message than just a stack trace.

**Comment by mehcode** [comment]
> Panics (including those caused by unwrap and other assertions) are used to indicate a programming error, in quick testing or in cases where using a normal Result is impossible (rare). A malformed configuration file or a file missing from the user's system is not a programming error.

You're technically right, but not practically in my instance. You should consider my use case. I asked what your specific use case is because I'm curious. I don't work on applications for the _average user_ but instead for _sys admins_ or myself. I normally work on medium to large web services. 

> Even if the location of the configuration file is hard-coded, the application may want to manually handle the errors if for example the configuration file is missing to give the user a friendlier error message than just a stack trace.

```rust
extern crate config;

fn main() {
    let settings = config::Config::default()
        .merge(config::File::with_name("Settings"))
        .merge(config::Environment::with_prefix("APP"))
        .unwrap();

    // [...]
}
```

Consider the above. Yes, it uses `.unwrap`, and yes, it will result in a panic in a number of cases.
 - `Settings.*` missing

```bash
❯ ./target/release/app
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: configuration file "Settings" not found
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

 - `Settings.*` parse failure

```bash
❯ ./target/release/simple
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: invalid number at line 1 in Settings.toml'
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Those error messages are _more than enough_ to help a system administrator (or myself) understand the issue when running the service in production.

Furthermore, in a production application, I'm going to have a global panic handler to report to bugsnag (or whatever service you're using). You can't control every piece of your app and there is always a chance it could panic somewhere. I could easily shorten the message and make it easier to read at the same time using a logging library.

```bash
❯ ./target/release/simple
Apr 02 20:20:19.721 CRIT invalid number at line 1 in Settings.toml
```

Now this is _my_ use case. I recognize that there are other uses cases which is why I try not to `.unwrap` internally in the library.

---

> Sorry for sounding harsh, but I wasted half an afternoon [...]

I apologize for the state of the library. It's not nearly done yet and I admit I should have let the chain API marinate longer before releasing (I committed it and released within hours). I'm only one person and I'm don't code in Rust nearly enough to fully understand how every scenario should be handled. I love feedback and I'll welcome discussion but let's keep it civil.

> It would not have been a problem if ConfigResult showed up in the docs,

I've never been very good at putting documentation together. The docs for this is probably the best I've ever done for a library of mine. I honestly didn't realize that I had to make sure a type was publicly exported to get documented. I assumed it was documented because it was used in the signature of a public method. 

---

> [...] Or is the reason for ConfigResult to exist to hide the existence of clone?

Exactly this. It looks really odd to me. Cloning a reference to a temporary like that is optimized away so it's not like its a performance hit but it still feels odd. I have a feeling that the needing to make it 2 lines is an issue in Rust that will eventually get worked on.

I'll play with it some more. Maybe I should just have a separate `ConfigBuilder` type that would allow for a clean one-line chain API and not make the Result type weird.

**Comment by mehcode** [comment]
@Jascha-N After looking at this again I decided to do what you suggested.

```rust
let mut settings = Config::new();
settings.merge(File::with_name("Settings"))?.merge(Environment::with_prefix("APP"))?
```

I dislike that the above is required when using the API as a chained API. However I imagine the majority of cases that are using this way are ending the chain with `.deserialize` (which will become `.try_into` soon) which wouldn't require binding `Config` with `let`.
