### ISSUE TITLE
Investigate ripping tree merging out into a separate crate

### ISSUE THREAD

**Issue by Phrohdoh** [mehcode/config-rs#40]

**Comment by mehcode** [comment]
@Phrohdoh Sorry for not getting back to you sooner. I got side-tracked and totally forgot about our conversation.

You can actually do what we were talking about now in v0.6 as follows:

```rust
config.merge(File::from_str(&String::from_utf8(your_bytes)?, FileFormat::Toml))?
```

----

As for actually moving the tree merge out into a crate.. 
 - https://github.com/mehcode/config-rs/blob/master/src/path/mod.rs#L136-L218
 - https://github.com/mehcode/config-rs/blob/master/src/source.rs#L16-L36
 - https://github.com/mehcode/config-rs/blob/master/src/source.rs#L74-L86

The merging is done following _setting_ via JSONPath and just iterating through keys. A generic JSONPath crate would need to invest in a compiler plugin or some heavy macros in order to adapt to a library or applications heterogeneous value enumeration. 

See https://github.com/mehcode/config-rs/blob/master/src/value.rs#L117-L139. A "map/table" in config is a `HashMap<String, Value>`. Deep merging needs to know a lot about my `Value` type in order to do the "deep" part.

Lots of serde libs have their own `Value` enum that changes slightly based on the capability of the underlying format.

I'll gladly use a crate if one comes out but I have no intention of doing so at this time.
