### ISSUE TITLE
Investigate ways to make CI faster

### ISSUE THREAD

**Issue by matthiasbeyer** [mehcode/config-rs#482]
I really don't like how slow CI is for this repository.

If someone wants to make CI faster, I'd love to see PRs for that!

**Comment by polarathene** [comment]
Just came across this, might be worth looking into if someone does tackle this:
- https://nexte.st/
- https://github.com/nextest-rs/nextest

I haven't worked with Rust with Github Actions, but I imagine you could cache some of the time consuming parts. I see in the actions history:
- Some jobs take 5 minutes to run `cargo --check`. Those seem to be for a specific MSRV version rather than stable/beta/nightly channels. Not sure why they are slower, perhaps Github has some cache proxy layer for the more common channels to save bandwidth? 🤷‍♂️ 
- Other jobs like `cargo clippy` and `cargo test` can take 1-2 minutes to download and compile the crates, which is the bulk of the jobs. Leveraging cache would help there a fair bit.

A quick look, [this action](https://github.com/marketplace/actions/rust-cache) seems to be a popular way to cache dependencies, benefits from a `Cargo.lock` being present, with only caveat being less useful on Nightly toolchain. So that should hopefully make a difference with https://github.com/mehcode/config-rs/pull/492 👍
