### ISSUE TITLE
Deserializing into a type with an unsigned integer doesn't give the expected result

### ISSUE THREAD

**Issue by repnop** [mehcode/config-rs#93]
Minimal example:

`main.rs`
```rust
use config::Config;
use serde::Deserialize;

#[derive(Deserialize)]
struct Foo {
    bar: u64,
}

fn main() {
    let mut settings = Config::new();
    settings.merge(config::File::with_name("test")).unwrap();
    
    let foo: Foo = settings.try_into().unwrap();
    println!("{}", foo.bar);
}
```
`test.toml`
```toml
bar = -1
```

Running this code produces `18446744073709551615` instead of erroring that the value was outside of the range of `u64`

**Comment by jcrevier** [comment]
Additionally, related to this is that values greater than `i64::max_value()` will fail to de-serialize into a u64.  The problem seems to be the Deserialize implementation uses the [`into_int()` ](https://docs.rs/config/0.10.1/config/struct.Value.html#method.into_int)method that converts everything into i64 then casts back to the needed type.

**Comment by kesyog** [comment]
Updated example:

```rs
use config::Config;
use serde::Deserialize;

#[derive(Deserialize)]
struct Foo {
    bar: u64,
}

fn main() {
    let settings = Config::builder()
        .add_source(config::File::with_name("test"))
        .build()
        .unwrap();

    let foo: Foo = settings.try_deserialize().unwrap();
    println!("{}", foo.bar);
}
```
